# Example configuration entry
esphome:
  name: inkplate

esp32:
  board: esp-wrover-kit

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: {}

captive_portal:

ota:

api:

text_sensor:
  - platform: homeassistant
    id: soc_ladewagen
    entity_id: sensor.ladewagensoc
    internal: true
  - platform: homeassistant
    id: soc_ioniq
    entity_id: sensor.evnotify_charge_status
    internal: true
  - platform: homeassistant
    id: soc_spring
    entity_id: sensor.battery_level
    internal: true
  - platform: homeassistant
    id: inkplate_battery_voltage
    entity_id: sensor.inkplate_battery_voltage
    internal: true

deep_sleep:
  run_duration: 22s
  sleep_duration: 1min


switch:
  - platform: restart
    name: "Inkplate Reboot"
    id: reboot

  - platform: gpio
    id: battery_read_mosfet
    pin:
      mcp23xxx: mcp23017_hub
      number: 9
      inverted: true

  - platform: template
    name: "Inkplate Greyscale mode"
    lambda: return id(inkplate_display).get_greyscale();
    turn_on_action:
      - lambda: id(inkplate_display).set_greyscale(true);
    turn_off_action:
      - lambda: id(inkplate_display).set_greyscale(false);

  - platform: template
    name: "Inkplate Partial Updating"
    lambda: return id(inkplate_display).get_partial_updating();
    turn_on_action:
      - lambda: id(inkplate_display).set_partial_updating(true);
    turn_off_action:
      - lambda: id(inkplate_display).set_partial_updating(false);

sensor:
  - platform: adc
    id: battery_voltage
    update_interval: never
    attenuation: 11db
    pin: 35
  - platform: template
    name: "Inkplate Battery Voltage"
    lambda: |-
      id(battery_read_mosfet).turn_on();
      delay(1);
      float adc = id(battery_voltage).sample();
      id(battery_read_mosfet).turn_off();
      return adc;
    filters:
      - multiply: 2

i2c:

mcp23017:
  - id: mcp23017_hub
    address: 0x20

binary_sensor:
  - platform: status
    name: "Inkplate Status"
    id: system_status

  - platform: gpio
    name: "Inkplate Touch Pad 1"
    pin:
      mcp23xxx: mcp23017_hub
      number: 10
  - platform: gpio
    name: "Inkplate Touch Pad 2"
    pin:
      mcp23xxx: mcp23017_hub
      number: 11
  - platform: gpio
    name: "Inkplate Touch Pad 3"
    pin:
      mcp23xxx: mcp23017_hub
      number: 12

time:
  - platform: sntp
    id: esptime

font:
  - file: "Arial.ttf"
    id: helvetica_96
    size: 96
  - file: "Arial.ttf"
    id: helvetica_48
    size: 48
  - file: "Arial.ttf"
    id: helvetica_24
    size: 24


display:
- platform: inkplate6
  id: inkplate_display
  greyscale: false
  partial_updating: false
  update_interval: 13s

  ckv_pin: 32
  sph_pin: 33
  gmod_pin:
    mcp23xxx: mcp23017_hub
    number: 1
  gpio0_enable_pin:
    mcp23xxx: mcp23017_hub
    number: 8
  oe_pin:
    mcp23xxx: mcp23017_hub
    number: 0
  spv_pin:
    mcp23xxx: mcp23017_hub
    number: 2
  powerup_pin:
    mcp23xxx: mcp23017_hub
    number: 4
  wakeup_pin:
    mcp23xxx: mcp23017_hub
    number: 3
  vcom_pin:
    mcp23xxx: mcp23017_hub
    number: 5

  lambda: |-
    it.fill(COLOR_ON);

    it.print(170, 70, id(helvetica_48), COLOR_OFF, TextAlign::BOTTOM_RIGHT, "Spring:");
    it.printf(180, 100, id(helvetica_96), COLOR_OFF, TextAlign::BOTTOM_LEFT, "%s%%", id(soc_spring).state.c_str());

    it.print(170, 220, id(helvetica_48), COLOR_OFF, TextAlign::BOTTOM_RIGHT, "Ioniq:");
    it.printf(180, 250, id(helvetica_96), COLOR_OFF, TextAlign::BOTTOM_LEFT, "%s%%", id(soc_ioniq).state.c_str());

    it.print(170, 370, id(helvetica_48), COLOR_OFF, TextAlign::BOTTOM_RIGHT, "Ladew.:");
    it.printf(180, 400, id(helvetica_96), COLOR_OFF, TextAlign::BOTTOM_LEFT, "%s%%", id(soc_ladewagen).state.c_str());

    it.rectangle(480, 5, 3, 400, COLOR_OFF);

    //it.strftime(800, 560, id(helvetica_96), COLOR_OFF, TextAlign::BOTTOM_RIGHT, "%H:%M", id(esptime).now());
    it.strftime(800, 600, id(helvetica_96), COLOR_OFF, TextAlign::BOTTOM_RIGHT, "%H:%M", id(esptime).now());

    it.printf(800, 0, id(helvetica_24), COLOR_OFF, TextAlign::TOP_RIGHT, "%sV", id(inkplate_battery_voltage).state.c_str());
