esphome:
  name: leiste
  on_boot:
      priority: -100
      then:
        - switch.turn_off: relay

esp8266:
  board: esp01_1m

wifi:
  networks:
  - ssid: WLAN
    password: !secret wifi_password
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  # use_address: 192.168.0.51
  ap: {}

captive_portal:

api:
  encryption:
    key: !secret api_encryption_key

logger:

ota:
  - platform: esphome

binary_sensor:
- platform: gpio
  pin:
    number: GPIO0
    mode:
      input: true
      pullup: true
    inverted: true
  name: "Leiste Button"
  on_press:
    - switch.toggle: relayled

- platform: status
  name: "Leiste Status"

switch:
- platform: template
  name: "Relay"
  optimistic: true
  id: relayled
  turn_on_action:
    - switch.turn_on: relay
    - light.turn_on: led
  turn_off_action:
    - switch.turn_off: relay
    - light.turn_off: led
- platform: gpio
  pin: GPIO12
  id: relay

output:
- platform: esp8266_pwm
  id: leiste_green_led
  pin: GPIO13
  inverted: true

light:
- platform: monochromatic
  name: "Leiste Green LED"
  output: leiste_green_led
  id: led
