esphome:
  name: s20-1
  on_boot:
      priority: -100
      then:
        - switch.turn_off: relay
        - delay: 300s
        - switch.turn_on: relay

esp8266:
  board: esp8285

wifi:
  networks:
  - ssid: ladewagen
    password: !secret wifi_password
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  # use_address: 192.168.0.51
  ap: {}

captive_portal:

api:
  encryption:
    key: !secret api_encryption_key

logger:

ota:

binary_sensor:
- platform: gpio
  pin:
    number: GPIO0
    mode:
      input: true
      pullup: true
    inverted: true
  name: "Sonoff S20 Button"
  on_press:
    - switch.toggle: relay
- platform: status
  name: "Sonoff S20 Status"


switch:
- platform: gpio
  name: "Sonoff S20 Relay"
  pin: GPIO12
  id: relay

output:
- platform: esp8266_pwm
  id: s20_green_led
  pin: GPIO13
  inverted: true

light:
- platform: monochromatic
  name: "Sonoff S20 Green LED"
  output: s20_green_led
