# Temperatur Messung mit EspLowPower Platine
# Nur R2,R4,R5,R6,R7 (10k) und R19 (330) und 10uF an 3.3V und Masse
# Dallas Chip anfänglich verpolt: Strom 1A er wurde heiss - funktioniert aber trotzdem noch
 
esphome:
  name: temphaus

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "HOXXs1eugzrjrsM1FQkvVvbvBjNNI5ZarXD1JpeEE2M="

ota:
  password: "e2b2c51869024ef64b70cb81d438e730"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temphaus Fallback Hotspot"
    password: "Bk1Ovr90Ycl9"

captive_portal:



# Nehme GPIO0, weil er mit 10k auf VCC gepulled ist
dallas:
  - pin: GPIO0
    update_interval: 5s
    
sensor:
  - platform: adc
    pin: VCC
    name: "VCC Voltage"
    update_interval: 5s

  - platform: dallas
    address: 0x7c1a6b6d0e64ff28
    name: "Temperatur"
