# Temperatur Messung mit EspLowPower Platine
# Nur R2,R4,R5,R6,R7 (10k) und R19 (330) und 10uF an 3.3V und Masse
# Dallas Chip anfänglich verpolt: Strom 1A er wurde heiss - funktioniert aber trotzdem noch
#
# Deep Sleep beenden: in Homassist Key e, dann Entty Suche prevent, dann einschalten
 
esphome:
  name: temphaus
  on_boot:
    then:
      - script.execute: consider_deep_sleep

esp8266:
  board: esp12e

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: "e2b2c51869024ef64b70cb81d438e730"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temphaus Fallback Hotspot"
    password: "Bk1Ovr90Ycl9"

captive_portal:



# Nehme GPIO0, weil er mit 10k auf VCC gepulled ist
dallas:
  - pin: GPIO0
    update_interval: 5s
    
sensor:
  - platform: adc
    pin: VCC
    name: "Haus VCC Voltage Temperatur Sensor"
    update_interval: 5s
    filters:
      - calibrate_linear:
        - 3.664 -> 3.496
        - 3.46 -> 3.297
        - 3.044 -> 2.897

  - platform: dallas
    #address: 0x7c1a6b6d0e64ff28
    index: 0
    name: "Haus Temperatur"

# Deep Sleep Ota enable:
# https://tatham.blog/2021/02/06/esphome-batteries-deep-sleep-and-over-the-air-updates/

deep_sleep:
  sleep_duration: 10min
  id: deep_sleep_temphaus

# Will only pick up a value if this device is configured in Home Assistant > Integrations
# If the device isn't configured, or Home Assistant is offline, it'll default to false
binary_sensor:
  - platform: homeassistant
    entity_id: input_boolean.prevent_deep_sleep
    id: prevent_deep_sleep

script:
  - id: consider_deep_sleep
    mode: queued
    then:
      - delay: 26s
      - if:
          condition:
            binary_sensor.is_on: prevent_deep_sleep
          then:
            - logger.log: 'Skipping sleep, per prevent_deep_sleep'
          else:
            - deep_sleep.enter: deep_sleep_temphaus
      - script.execute: consider_deep_sleep
