esphome:
  name: tv-ir-remote
  friendly_name: TV IR Remote

esp8266:
  board: esp8285
 
# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome

wifi:
  networks:
  - ssid: WLAN
    password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails                                                                                                                                                               
  ap:
    ssid: $name

captive_portal:

#remote_receiver:
#  pin:
#    number: GPIO14
#    inverted: true
#  dump: all

remote_transmitter:
  pin:
    number: GPIO4
  carrier_duty_percent: 50%

# Nur NEC Protokoll ging
button:
  - platform: template
    name: "On/Off"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0xF708
          command_repeats: 1
