# Steuert Vestel Wallbox
# Aus/Einschalten über D8
#
 
esphome:
  name: vestel_wallbox

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: "e2b2c51869024ef64b70cb81d438e730"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temphaus Fallback Hotspot"
    password: "Bk1Ovr90Ycl9"

captive_portal:



switch:
  - platform: gpio
    pin: 
      number: D7
    name: "Vestel 8A charging"
    device_class: switch
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: 
      number: D8
      inverted: true
    name: "Vestel allow charging"
    id: sw_allow_charging
    device_class: switch
    restore_mode: ALWAYS_ON

binary_sensor:
  - platform: gpio
    pin:
      number: D6
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Vestel allow button"
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.turn_on: sw_allow_charging
